# Generated by Django 4.1.1 on 2022-10-03 18:09

import django.core.validators
from django.db import migrations, models
import dogs.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('species', models.CharField(choices=[('1', 'Canis lupus familiaris'), ('2', 'Felis catus'), ('3', 'Cricetinae')], max_length=1)),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1950), dogs.models.max_value_current_year], verbose_name='year')),
            ],
        ),
    ]
