# Generated by Django 4.1.1 on 2022-10-03 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pets',
            name='species',
            field=models.CharField(choices=[('1', 'dog'), ('2', 'cat'), ('3', 'hamster')], max_length=1),
        ),
    ]
